### ISSUE TITLE
Source build and docker instructions don't work

### ISSUE THREAD

**Issue by popey** [bitbomdev/minefield#79]
I tried building from source, using the instructions in the README.

```bash
$ ./minefield ingest sbom cloudbees_sboms/basic-platform.json
Error: failed to ingest SBOM: errors occurred during SBOM ingestion: [failed to process SBOM file cloudbees_sboms/basic-platform.json: failed to add node: failed to generate ID: failed to generate ID: dial tcp 127.0.0.1:6379: connect: connection refused]
panic: failed to ingest SBOM: errors occurred during SBOM ingestion: [failed to process SBOM file cloudbees_sboms/basic-platform.json: failed to add node: failed to generate ID: failed to generate ID: dial tcp 127.0.0.1:6379: connect: connection refused]

goroutine 1 [running]:
main.main.func1({0x100c0dbc8?, 0x140000de180?}, {0x100c025a8, 0x140000bc7e0})
	/Users/alan/Work/bitbomdev/minefield/main.go:34 +0x148
reflect.Value.call({0x100aebca0?, 0x140000dc0d8?, 0x140000d7b00?}, {0x10094faf3, 0x4}, {0x140000d7bf0, 0x2, 0x1016010e8?})
	/Users/alan/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.5.darwin-arm64/src/reflect/value.go:596 +0x970
reflect.Value.Call({0x100aebca0?, 0x140000dc0d8?, 0x8?}, {0x140000d7bf0?, 0x140000b8401?, 0x140000d7bf0?})
	/Users/alan/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.5.darwin-arm64/src/reflect/value.go:380 +0x94
go.uber.org/dig.defaultInvoker({0x100aebca0?, 0x140000dc0d8?, 0x140000b84a0?}, {0x140000d7bf0?, 0x2?, 0x100c0f4f0?})
	/Users/alan/go/pkg/mod/go.uber.org/dig@v1.18.0/container.go:257 +0x28
go.uber.org/dig.(*Scope).Invoke(0x140000c80b0, {0x100aebca0, 0x140000dc0d8}, {0x0, 0x0, 0x1010f3f80?})
	/Users/alan/go/pkg/mod/go.uber.org/dig@v1.18.0/invoke.go:161 +0x4bc
go.uber.org/dig.(*Container).Invoke(0x1010f3f70?, {0x100aebca0?, 0x140000dc0d8?}, {0x0?, 0x140000b8480?, 0x0?})
	/Users/alan/go/pkg/mod/go.uber.org/dig@v1.18.0/invoke.go:83 +0x2c
go.uber.org/fx.runInvoke({0x101603fc8?, 0x140000de050?}, {{0x100aebca0, 0x140000dc0d8}, {0x140000e6000, 0x2, 0x3}})
	/Users/alan/go/pkg/mod/go.uber.org/fx@v1.22.2/invoke.go:109 +0x138
go.uber.org/fx.(*module).executeInvoke(0x140000c21a0, {{0x100aebca0, 0x140000dc0d8}, {0x140000e6000, 0x2, 0x3}})
	/Users/alan/go/pkg/mod/go.uber.org/fx@v1.22.2/module.go:320 +0x118
go.uber.org/fx.(*module).executeInvokes(0x140000c21a0)
	/Users/alan/go/pkg/mod/go.uber.org/fx@v1.22.2/module.go:306 +0xd0
go.uber.org/fx.New({0x14000049eb0, 0x3, 0x140000021c0?})
	/Users/alan/go/pkg/mod/go.uber.org/fx@v1.22.2/app.go:517 +0x7e4
main.main()
	/Users/alan/Work/bitbomdev/minefield/main.go:19 +0x184
```

Is it looking for a redis db?

Okay, let's try the docker container:

```bash
$ docker pull ghcr.io/bit-bom/minefield:latest

Error response from daemon: Head "https://ghcr.io/v2/bit-bom/minefield/manifests/latest": denied: denied
```

Did the name change?

```bash
$ docker pull ghcr.io/bitbomdev/minefield:latest

Error response from daemon: Head "https://ghcr.io/v2/bitbomdev/minefield/manifests/latest": denied: denied

```

What's the magic voodoo required to launch this? :D

**Comment by neilnaveen** [comment]
@popey  Thanks for reaching out! We have addresed the README with the instructions.
 
 >Is it looking for a redis db?
 
 Yes, it is looking for the Redis and you should be able to start it with https://github.com/bitbomdev/minefield/blob/fc0a072f6c3deda29745cf97802571a6d32e2a5f/Makefile#L22
 
 >docker pull ghcr.io/bitbomdev/minefield:latest
 
 The most likely reason that you are getting this error is that you aren't signed into ghcr in your terminal.
 
 ```
$ docker pull ghcr.io/bitbomdev/minefield:latest

latest: Pulling from bitbomdev/minefield
878e6d1d3d25: Pull complete 
bc02531dc044: Pull complete 
1d6bcb24be5c: Pull complete 
Digest: sha256:9ec60fb1b61d2f418733da026738bc41c65dc00793e94b8b32aea2842fdc6dfb
Status: Downloaded newer image for ghcr.io/bitbomdev/minefield:latest
ghcr.io/bitbomdev/minefield:latest
```
